# Generated by Django 4.2.13 on 2024-07-08 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
        ('todoitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='item',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todoitem', to='todolist.todolist'),
            preserve_default=False,
        ),
    ]
