# Generated by Django 4.2.13 on 2024-07-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoitem', '0002_todoitem_item_todoitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='user',
            new_name='todolist',
        ),
    ]
